from turtle import *


def draw(canvas, weather):
    t = RawTurtle(canvas)
    t.speed(0)
    t.hideturtle()
    t.penup()
    t.setposition(-50, 50)
    if weather == 'Clear':
        t.pendown()
        t.fillcolor("blue")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        t.penup()
        t.setpos(0, -10)
        t.color('yellow')
        t.fillcolor('yellow')
        t.pendown()
        t.begin_fill()
        t.circle(20)
        t.end_fill()
    elif weather == 'Thunderstorm':
        # draw background
        t.pendown()
        t.fillcolor("dark grey")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        # draw rain cloud
        t.penup()
        t.setposition(0, 20)
        t.pendown()
        t.fillcolor('grey')
        t.color('grey')
        t.begin_fill()
        t.circle(12)
        t.setposition(10, 20)
        t.circle(10)
        t.setposition(-15, 20)
        t.circle(8)
        t.setposition(-10, 20)
        t.circle(8)
        t.end_fill()
        # draw rain
        t.penup()
        t.setposition(5, 15)
        t.dot(3, "blue")
        t.setposition(15, 12)
        t.dot(3, "blue")
        t.setposition(-6, 13)
        t.dot(3, "blue")
        t.setposition(-20, 10)
        t.dot(3, "blue")
        t.setposition(-6, 0)
        t.dot(3, "blue")
        t.setposition(6, 2)
        t.dot(3, "blue")
        # draw lightning
        t.setposition(0, 20)
        t.setheading(0)
        t.right(45)
        t.pendown()
        t.fillcolor('yellow')
        t.color('yellow')
        t.begin_fill()
        t.forward(25)
        t.left(60)
        t.forward(5)
        t.right(90)
        t.forward(15)
        t.left(150)
        t.forward(25)
        t.left(120)
        t.forward(15)
        t.setposition(10, 20)
        t.setposition(0, 20)
        t.end_fill()
    elif weather == 'Drizzle':
        # draw background
        t.pendown()
        t.fillcolor("light blue")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        # draw rain cloud
        t.penup()
        t.setposition(0, 20)
        t.pendown()
        t.fillcolor('white')
        t.color('white')
        t.begin_fill()
        t.circle(12)
        t.setposition(10, 20)
        t.circle(10)
        t.setposition(-15, 20)
        t.circle(8)
        t.setposition(-10, 20)
        t.circle(8)
        t.end_fill()
        # draw rain
        t.penup()
        t.setposition(5, 15)
        t.dot(3, "blue")
        t.setposition(15, 12)
        t.dot(3, "blue")
        t.setposition(-6, 13)
        t.dot(3, "blue")
        t.setposition(-3, 18)
        t.dot(3, "blue")
        t.setposition(-20, 10)
        t.dot(3, "blue")
        t.setposition(4, 8)
        t.dot(3, "blue")
        t.setposition(-9, 8)
        t.dot(3, "blue")
        t.setposition(-6, 0)
        t.dot(3, "blue")
        t.setposition(6, 2)
        t.dot(3, "blue")
    elif weather == 'Rain':
        # draw background
        t.pendown()
        t.fillcolor("dark grey")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        # draw rain cloud
        t.penup()
        t.setposition(0, 20)
        t.pendown()
        t.fillcolor('grey')
        t.color('grey')
        t.begin_fill()
        t.circle(12)
        t.setposition(10, 20)
        t.circle(10)
        t.setposition(-15, 20)
        t.circle(8)
        t.setposition(-10, 20)
        t.circle(8)
        t.end_fill()
        # draw rain
        t.penup()
        t.setposition(5, 15)
        t.dot(3, "blue")
        t.setposition(15, 12)
        t.dot(3, "blue")
        t.setposition(-6, 13)
        t.dot(3, "blue")
        t.setposition(-3, 18)
        t.dot(3, "blue")
        t.setposition(-20, 10)
        t.dot(3, "blue")
        t.setposition(4, 8)
        t.dot(3, "blue")
        t.setposition(-9, 8)
        t.dot(3, "blue")
        t.setposition(-6, 0)
        t.dot(3, "blue")
        t.setposition(6, 2)
        t.dot(3, "blue")
    elif weather == 'Snow':
        # set background
        t.pendown()
        t.fillcolor("grey")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        # draw snow cloud
        t.penup()
        t.setposition(0, 20)
        t.pendown()
        t.fillcolor('white')
        t.color('white')
        t.begin_fill()
        t.circle(12)
        t.setposition(10, 20)
        t.circle(10)
        t.setposition(-15, 20)
        t.circle(8)
        t.setposition(-10, 20)
        t.circle(8)
        t.end_fill()
        # draw snow
        t.penup()
        t.setposition(5, 15)
        t.dot(3, "white")
        t.setposition(15, 12)
        t.dot(3, "white")
        t.setposition(-6, 13)
        t.dot(3, "white")
        t.setposition(-3, 18)
        t.dot(3, "white")
        t.setposition(-20, 10)
        t.dot(3, "white")
        t.setposition(4, 8)
        t.dot(3, "white")
        t.setposition(-9, 8)
        t.dot(3, "white")
        t.setposition(-6, 0)
        t.dot(3, "white")
        t.setposition(6, 2)
        t.dot(3, "white")
    elif weather == 'Clouds':
        # sets background
        t.pendown()
        t.fillcolor("blue")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        # draw cloud
        t.penup()
        t.home()
        t.fillcolor("white")
        t.color("white")
        t.begin_fill()
        t.pendown()
        t.circle(15)
        t.end_fill()
        t.setposition(-15, -10)
        t.begin_fill()
        t.circle(12)
        t.end_fill()
        t.setposition(20, -10)
        t.begin_fill()
        t.circle(12)
        t.end_fill()
        t.setposition(-15, -10)
        t.begin_fill()
        t.heading()
        t.forward(35)
        t.left(90)
        t.forward(13)
        t.left(90)
        t.forward(35)
        t.left(90)
        t.forward(13)
        t.end_fill()

    else:
        t.pendown()
        t.fillcolor("dark grey")
        t.begin_fill()
        for x in range(4):
            t.forward(100)
            t.right(90)
        t.end_fill()
        # draw cloud
        t.penup()
        t.setposition(0, 20)
        t.pendown()
        t.fillcolor('grey')
        t.color('grey')
        t.begin_fill()
        t.circle(12)
        t.setposition(10, 20)
        t.circle(10)
        t.setposition(-15, 20)
        t.circle(8)
        t.setposition(-10, 20)
        t.circle(8)
        t.end_fill()
